-- 1. Ejecuta este script en el "SQL Editor" de tu proyecto en Supabase (supabase.com)

-- Crear tabla USUARIO (si no existe)
CREATE TABLE IF NOT EXISTS "USUARIO" (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    contrasena VARCHAR(255) NOT NULL,
    correo VARCHAR(100),
    rol VARCHAR(50) DEFAULT 'usuario',
    activo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Insertar los usuarios solicitados
-- NOTA: Emmanuel no tenía contraseña especificada, se asignó '123456' temporalmente.
INSERT INTO "USUARIO" (nombre, contrasena, rol, correo)
VALUES 
    ('Romel', 'fornai', 'admin', 'romelcomparta09@gmail.com'),
    ('Elias', 'rocket', 'admin', 'eliasderas130@gmail.com'),
    ('Angel', 'wuwa', 'admin', 'mirandosa1234@gmail.com'),
    ('Emmanuel', '123456', 'admin', NULL),
    ('Jesus Alberto', 'oberwash', 'admin', 'jesusalbertosenabraisnavarro@gmail.com')
ON CONFLICT (nombre) DO UPDATE 
SET contrasena = EXCLUDED.contrasena,
    correo = EXCLUDED.correo;

-- Habilitar Row Level Security (RLS) para seguridad básica
ALTER TABLE "USUARIO" ENABLE ROW LEVEL SECURITY;

-- Política para permitir lectura pública (para el login simple)
-- En producción, esto debería ser más estricto.
CREATE POLICY "Permitir lectura publica de usuarios" 
ON "USUARIO" FOR SELECT 
USING (true);
