-- 1. Ejecuta este script en el "SQL Editor" de tu proyecto en Supabase (supabase.com)

-- Limpiar tablas existentes (Cuidado: Esto borra todos los datos y reinicia el esquema)
DROP TABLE IF EXISTS "FACTURA_DETALLE" CASCADE;
DROP TABLE IF EXISTS "FACTURA" CASCADE;
DROP TABLE IF EXISTS "ORDEN_DETALLE" CASCADE;
DROP TABLE IF EXISTS "CITA" CASCADE;
DROP TABLE IF EXISTS "ORDEN_SERVICIO" CASCADE;
DROP TABLE IF EXISTS "SERVICIO" CASCADE;
DROP TABLE IF EXISTS "DATOS_FACTURACION" CASCADE;
DROP TABLE IF EXISTS "CLIENTE" CASCADE;
DROP TABLE IF EXISTS "USUARIO" CASCADE;
DROP TABLE IF EXISTS "CAT_METODO_PAGO" CASCADE;
DROP TABLE IF EXISTS "CAT_ESTADO" CASCADE;

-- Eliminar tipos si existen
DROP TYPE IF EXISTS "tipo_estado_enum";
DROP TYPE IF EXISTS "tipo_cliente_enum";

-- Crear Tipos ENUM
CREATE TYPE "tipo_estado_enum" AS ENUM ('CITA', 'ORDEN', 'VENTA');
CREATE TYPE "tipo_cliente_enum" AS ENUM ('Persona', 'Empresa');

-- 1. CAT_ESTADO
CREATE TABLE "CAT_ESTADO" (
    "id_estado" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(50) NOT NULL UNIQUE,
    "tipo" "tipo_estado_enum" NOT NULL,
    "descripcion" VARCHAR(100)
);

-- 2. CAT_METODO_PAGO
CREATE TABLE "CAT_METODO_PAGO" (
    "id_metodo_pago" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(50) NOT NULL UNIQUE,
    "descripcion" VARCHAR(100)
);

-- 3. USUARIO
CREATE TABLE "USUARIO" (
    "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(100) NOT NULL,
    "apellido_paterno" VARCHAR(100) NOT NULL,
    "apellido_materno" VARCHAR(100),
    "correo" VARCHAR(100) NOT NULL UNIQUE,
    "contrasena" VARCHAR(255) NOT NULL,
    "telefono" VARCHAR(20),
    "activo" BOOLEAN DEFAULT TRUE,
    "fecha_registro" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. CLIENTE
CREATE TABLE "CLIENTE" (
    "id_cliente" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" "tipo_cliente_enum" NOT NULL,
    "nombre" VARCHAR(100) NOT NULL,
    "apellido_paterno" VARCHAR(100),
    "apellido_materno" VARCHAR(100),
    "telefono" VARCHAR(20),
    "correo" VARCHAR(100),
    "direccion" VARCHAR(100),
    "codigo_postal" VARCHAR(10),
    "activo" BOOLEAN DEFAULT TRUE,
    "fecha_registro" DATE DEFAULT CURRENT_DATE
);

-- 5. DATOS_FACTURACION
CREATE TABLE "DATOS_FACTURACION" (
    "id_datos_facturacion" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_cliente" BIGINT NOT NULL REFERENCES "CLIENTE"("id_cliente"),
    "razon_social" VARCHAR(150) NOT NULL,
    "rfc" VARCHAR(13) NOT NULL,
    "regimen_fiscal" VARCHAR(100),
    "uso_cfdi" VARCHAR(10) DEFAULT 'G03',
    "calle" VARCHAR(100),
    "numero_exterior" VARCHAR(20),
    "numero_interior" VARCHAR(20),
    "colonia" VARCHAR(100),
    "codigo_postal" VARCHAR(10)
);

-- 6. SERVICIO
CREATE TABLE "SERVICIO" (
    "id_servicio" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nombre" VARCHAR(100) NOT NULL,
    "descripcion" TEXT,
    "precio" DECIMAL(10,2) NOT NULL,
    "tiempo_estimado" INT NOT NULL, -- En minutos
    "activo" BOOLEAN DEFAULT TRUE
);

-- 7. ORDEN_SERVICIO
CREATE TABLE "ORDEN_SERVICIO" (
    "id_orden" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_cliente" BIGINT NOT NULL REFERENCES "CLIENTE"("id_cliente"),
    "id_usuario" BIGINT NOT NULL REFERENCES "USUARIO"("id_usuario"),
    "id_estado" BIGINT NOT NULL REFERENCES "CAT_ESTADO"("id_estado"),
    "fecha_inicio" TIMESTAMP WITH TIME ZONE NOT NULL,
    "fecha_fin" TIMESTAMP WITH TIME ZONE,
    "subtotal" DECIMAL(10,2) NOT NULL,
    "descuento" DECIMAL(10,2) DEFAULT 0,
    "total" DECIMAL(10,2) NOT NULL,
    "observaciones" TEXT
);

-- 8. ORDEN_DETALLE
CREATE TABLE "ORDEN_DETALLE" (
    "id_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_orden" BIGINT NOT NULL REFERENCES "ORDEN_SERVICIO"("id_orden"),
    "id_servicio" BIGINT NOT NULL REFERENCES "SERVICIO"("id_servicio"),
    "cantidad" INT DEFAULT 1,
    "precio_unitario" DECIMAL(10,2) NOT NULL,
    "subtotal" DECIMAL(10,2) NOT NULL,
    "descuento" DECIMAL(10,2) DEFAULT 0,
    "total" DECIMAL(10,2) NOT NULL,
    "observaciones" TEXT
);

-- 9. CITA
CREATE TABLE "CITA" (
    "id_cita" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_estado" BIGINT NOT NULL REFERENCES "CAT_ESTADO"("id_estado"),
    "id_orden" BIGINT NOT NULL UNIQUE REFERENCES "ORDEN_SERVICIO"("id_orden"),
    "fecha" DATE NOT NULL,
    "hora" TIME NOT NULL,
    "observaciones" TEXT,
    "fecha_creacion" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 10. FACTURA
CREATE TABLE "FACTURA" (
    "id_factura" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_metodo_pago" BIGINT NOT NULL REFERENCES "CAT_METODO_PAGO"("id_metodo_pago"),
    "id_datos_facturacion" BIGINT NOT NULL REFERENCES "DATOS_FACTURACION"("id_datos_facturacion"),
    "folio" VARCHAR(50) NOT NULL UNIQUE,
    "uuid" VARCHAR(36) UNIQUE,
    "fecha_emision" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "subtotal" DECIMAL(10,2) NOT NULL,
    "impuestos" DECIMAL(10,2) NOT NULL,
    "total" DECIMAL(10,2) NOT NULL,
    "ruta_xml" VARCHAR(255),
    "ruta_pdf" VARCHAR(255)
);

-- 11. FACTURA_DETALLE
CREATE TABLE "FACTURA_DETALLE" (
    "id_factura_detalle" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_factura" BIGINT NOT NULL REFERENCES "FACTURA"("id_factura"),
    "id_orden_detalle" BIGINT NOT NULL REFERENCES "ORDEN_DETALLE"("id_detalle"),
    "clave_producto" VARCHAR(20),
    "clave_unidad" VARCHAR(10) DEFAULT 'E48',
    "descripcion" VARCHAR(200) NOT NULL,
    "cantidad" DECIMAL(10,2) NOT NULL,
    "precio_unitario" DECIMAL(10,2) NOT NULL,
    "subtotal" DECIMAL(10,2) NOT NULL,
    "impuestos" DECIMAL(10,2) NOT NULL,
    "total" DECIMAL(10,2) NOT NULL
);

-- Habilitar Row Level Security (RLS) en todas las tablas
ALTER TABLE "CAT_ESTADO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CAT_METODO_PAGO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "USUARIO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CLIENTE" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DATOS_FACTURACION" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SERVICIO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ORDEN_SERVICIO" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ORDEN_DETALLE" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CITA" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FACTURA" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FACTURA_DETALLE" ENABLE ROW LEVEL SECURITY;

-- Políticas de lectura pública (Para desarrollo, ajustar en producción)
CREATE POLICY "Public Read CAT_ESTADO" ON "CAT_ESTADO" FOR SELECT USING (true);
CREATE POLICY "Public Read CAT_METODO_PAGO" ON "CAT_METODO_PAGO" FOR SELECT USING (true);
CREATE POLICY "Public Read USUARIO" ON "USUARIO" FOR SELECT USING (true);
CREATE POLICY "Public Read CLIENTE" ON "CLIENTE" FOR SELECT USING (true);
CREATE POLICY "Public Read DATOS_FACTURACION" ON "DATOS_FACTURACION" FOR SELECT USING (true);
CREATE POLICY "Public Read SERVICIO" ON "SERVICIO" FOR SELECT USING (true);
CREATE POLICY "Public Read ORDEN_SERVICIO" ON "ORDEN_SERVICIO" FOR SELECT USING (true);
CREATE POLICY "Public Read ORDEN_DETALLE" ON "ORDEN_DETALLE" FOR SELECT USING (true);
CREATE POLICY "Public Read CITA" ON "CITA" FOR SELECT USING (true);
CREATE POLICY "Public Read FACTURA" ON "FACTURA" FOR SELECT USING (true);
CREATE POLICY "Public Read FACTURA_DETALLE" ON "FACTURA_DETALLE" FOR SELECT USING (true);

-- Insertar Datos Iniciales (Seed)

-- Estados Iniciales
INSERT INTO "CAT_ESTADO" (nombre, tipo, descripcion) VALUES
('Pendiente', 'CITA', 'Cita agendada pero no realizada'),
('Confirmada', 'CITA', 'Cita confirmada por el cliente'),
('Cancelada', 'CITA', 'Cita cancelada'),
('En Proceso', 'ORDEN', 'Servicio en curso'),
('Terminada', 'ORDEN', 'Servicio finalizado'),
('Pagada', 'VENTA', 'Venta cobrada');

-- Métodos de Pago SAT
INSERT INTO "CAT_METODO_PAGO" (nombre, descripcion) VALUES
('01', 'Efectivo'),
('03', 'Transferencia electrónica de fondos'),
('04', 'Tarjeta de crédito'),
('28', 'Tarjeta de débito');

-- Usuarios Iniciales
-- Nota: Se agregó 'Admin' como apellido paterno para cumplir con la restricción NOT NULL.
-- Por favor actualizar con los apellidos reales posteriormente.
INSERT INTO "USUARIO" (nombre, apellido_paterno, correo, contrasena) VALUES
('Romel', 'Admin', 'romelcomparta09@gmail.com', 'fornai'),
('Elias', 'Admin', 'eliasderas130@gmail.com', 'rocket'),
('Angel', 'Admin', 'mirandosa1234@gmail.com', 'wuwa'),
('Emmanuel', 'Admin', 'emmanuel@temp.com', '123456'),
('Jesus Alberto', 'Admin', 'jesusalbertosenabraisnavarro@gmail.com', 'oberwash');
